# Generated by Django 6.0.6 on 2026-06-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0010_delete_amin_delete_candidatein_delete_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
