# Generated by Django 6.0.6 on 2026-06-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0011_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'active_session_table',
            },
        ),
        migrations.AddField(
            model_name='signup',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
