# Generated by Django 6.0.6 on 2026-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0012_activesession_signup_voted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
        migrations.AddField(
            model_name='signup',
            name='aadhar',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='signup',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
