# Generated by Django 6.0.5 on 2026-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0014_candidate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='voted_party',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
