# Generated by Django 5.2.5 on 2026-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aminapp', '0016_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='voter_id',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
